QUEUE_VIDEO_DOWNLOAD = "video.download"
QUEUE_VIDEO_AUDIO_EXTRACT = "video.audio.extract"
QUEUE_VIDEO_THUMBNAIL_GENERATE = "video.thumbnail.generate"
QUEUE_VIDEO_TRANSCRIBE = "video.transcribe"
QUEUE_VIDEO_SUMMARIZE = "video.summarize"
QUEUE_VIDEO_TAGS = "video.tags"
QUEUE_VIDEO_FAILED = "video.failed"
QUEUE_VIDEO_STATUS = "video.status"

ALL_QUEUES = [
    QUEUE_VIDEO_DOWNLOAD,
    QUEUE_VIDEO_AUDIO_EXTRACT,
    QUEUE_VIDEO_THUMBNAIL_GENERATE,
    QUEUE_VIDEO_TRANSCRIBE,
    QUEUE_VIDEO_SUMMARIZE,
    QUEUE_VIDEO_TAGS,
    QUEUE_VIDEO_FAILED,
    QUEUE_VIDEO_STATUS,
]
